# -*- coding: utf-8 -*-
"""PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15O9Wo_4wmWMmxXB0end7vLJChL2vHXG7
"""

import pandas as pd
import json
import xml.etree.ElementTree as ET
import re
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import os

# Ensure python-evtx is installed before importing Evtx
!pip install python-evtx -q
!pip install groq -q

from Evtx.Evtx import Evtx
from groq import Groq
from google.colab import userdata
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import numpy as np

MITRE_MAPPINGS = {
        "powershell":       ("T1059.001", "Command and Scripting Interpreter: PowerShell",    "Execution"),
        "wscript":          ("T1059.005", "Command and Scripting Interpreter: VBScript",       "Execution"),
        ".vbs":             ("T1059.005", "Command and Scripting Interpreter: VBScript",       "Execution"),
        "cmd.exe":          ("T1059.003", "Command and Scripting Interpreter: Windows CMD",    "Execution"),
        "mimikatz":         ("T1003.001", "OS Credential Dumping: LSASS Memory",              "Credential Access"),
        "empire":           ("T1059.001", "Command and Scripting Interpreter: PowerShell",    "Execution"),
        "1102":             ("T1070.001", "Indicator Removal: Clear Windows Event Logs",      "Defense Evasion"),
        "7045":             ("T1543.003", "Create or Modify System Process: Windows Service", "Persistence"),
        "conhost":          ("T1059.003", "Command and Scripting Interpreter: Windows CMD",   "Execution"),
        "net.exe":          ("T1069.001", "Permission Groups Discovery: Local Groups",        "Discovery"),
        "whoami":           ("T1033",     "System Owner/User Discovery",                      "Discovery"),
        "schtasks":         ("T1053.005", "Scheduled Task/Job: Scheduled Task",              "Persistence"),
        "reg.exe":          ("T1112",     "Modify Registry",                                  "Defense Evasion")
      }

# Define global constants for file paths
PROJECT_PATH = "/content/drive/MyDrive/AI_Forensic_Project"
BASE = f"{PROJECT_PATH}/evidence/local/windows_logs"
MORDOR_JSON_PATH = '/content/drive/MyDrive/AI_Forensic_Project/evidence/mordor/empire_launcher_vbs_2020-09-04160940.json'
SECURITY_EVTX_PATH = f"{BASE}/security_local.evtx"
SYSTEM_EVTX_PATH = f"{BASE}/system_local.evtx"
SECURITY_JSON_OUTPUT_PATH = f"{BASE}/security.json"
SYSTEM_JSON_OUTPUT_PATH = f"{BASE}/system.json"
OUTPUT_DIR = f"{PROJECT_PATH}/timeline_output"

def evtx_to_json_stream(evtx_file, output_file):
    with Evtx(evtx_file) as log:
        with open(output_file, "w", encoding="utf-8") as f:
            for record in log.records():
                f.write(json.dumps(record.xml()) + "\n")

def parse_security_event_xml(xml_string):
    event_data = {}
    try:
        root = ET.fromstring(xml_string)
        namespaces = {
            'win': 'http://schemas.microsoft.com/win/2004/08/events/event'
        }
        event_id_element = root.find('.//win:EventID', namespaces=namespaces)
        if event_id_element is not None:
            event_data['EventID'] = event_id_element.text
        time_created_element = root.find('.//win:TimeCreated', namespaces=namespaces)
        if time_created_element is not None:
            event_data['EventTime'] = time_created_element.get('SystemTime')
        provider_name_element = root.find('.//win:Provider', namespaces=namespaces)
        if provider_name_element is not None:
            event_data['ProviderName'] = provider_name_element.get('Name')
        event_data_element = root.find('.//win:EventData', namespaces=namespaces)
        if event_data_element is not None:
            for data_element in event_data_element.findall('win:Data', namespaces=namespaces):
                name = data_element.get('Name')
                value = data_element.text
                if name and value:
                    event_data[name] = value
        user_data_element = root.find('.//win:UserData', namespaces=namespaces)
        if user_data_element is not None:
            for child in user_data_element:
                if child.tag:
                    tag_name = child.tag.split('}')[-1]
                    event_data[tag_name] = child.text
    except ET.ParseError:
        pass
    return event_data

def parse_system_event_xml(xml_string):
    event_data = {}
    try:
        root = ET.fromstring(xml_string)
        namespaces = {
            'win': 'http://schemas.microsoft.com/win/2004/08/events/event'
        }
        event_id_element = root.find('.//win:EventID', namespaces=namespaces)
        if event_id_element is not None:
            event_data['EventID'] = event_id_element.text
        time_created_element = root.find('.//win:TimeCreated', namespaces=namespaces)
        if time_created_element is not None:
            event_data['EventTime'] = time_created_element.get('SystemTime')
        provider_name_element = root.find('.//win:Provider', namespaces=namespaces)
        if provider_name_element is not None:
            event_data['ProviderName'] = provider_name_element.get('Name')
        event_data_element = root.find('.//win:EventData', namespaces=namespaces)
        if event_data_element is not None:
            for data_element in event_data_element.findall('win:Data', namespaces=namespaces):
                name = data_element.get('Name')
                value = data_element.text
                if name and value:
                    event_data[name] = value
        user_data_element = root.find('.//win:UserData', namespaces=namespaces)
        if user_data_element is not None:
            for child in user_data_element:
                if child.tag:
                    tag_name = child.tag.split('}')[-1]
                    event_data[tag_name] = child.text
    except ET.ParseError:
        pass
    return event_data

def extract_process(desc):
    match = re.search(r'[\\/]([^\\/]+\.exe)', str(desc), re.IGNORECASE)
    if match:
        return match.group(1).lower()
    match = re.search(r'([A-Za-z0-9_\-]+\.exe)', str(desc), re.IGNORECASE)
    if match:
        return match.group(1).lower()
    return "unknown"

def hunt_threats(row):
    desc = str(row['Description']).lower()
    source = str(row['Source']).lower()
    event_id = str(row['EventID'])

    if event_id == '1102':
        return "CRITICAL: Audit Logs Cleared (Defense Evasion)"
    elif event_id == '7045':
        return "WARNING: New Service Installed (Potential Persistence)"

    suspicious_keywords = ['powershell', 'cmd.exe', '.vbs', 'empire', 'mimikatz']
    for keyword in suspicious_keywords:
        if keyword in desc:
            return f"ALERT: Suspicious Keyword ({keyword})"

    if event_id == '1' and 'sysmon' in source:
         return "INFO: Process Created"

    return "Normal"

def map_to_mitre(row):
    desc = str(row["Description"]).lower()
    event_id = str(row["EventID"])

    if event_id in MITRE_MAPPINGS:
        tid, name, tactic = MITRE_MAPPINGS[event_id]
        return pd.Series([tid, name, tactic])

    for keyword, (tid, name, tactic) in MITRE_MAPPINGS.items():
        if keyword in desc:
            return pd.Series([tid, name, tactic])

    return pd.Series(["—", "Unclassified Activity", "Unknown"])

def build_attack_chains(df, time_gap_minutes=2):
    df = df.sort_values("Timestamp").copy()

    chain_id = 0
    chains = []
    prev_time = None

    for _, row in df.iterrows():
        curr_time = row["Timestamp"]

        if prev_time is None or (curr_time - prev_time) > pd.Timedelta(minutes=time_gap_minutes):
            chain_id += 1

        chains.append(chain_id)
        prev_time = curr_time

    df["AttackChainID"] = chains
    return df

def build_report_context(ml_full, chain_risk):
    top_anomalies = ml_full[ml_full["AnomalyScore_raw"] == -1].nlargest(5, "RiskScore")[
        ["Timestamp", "ProcessName", "MITRE_ID", "MITRE_Technique", "MITRE_Tactic", "RiskScore", "Description"]
    ].to_dict(orient="records")

    technique_summary = ml_full[ml_full["MITRE_ID"] != "—"].groupby(
        ["MITRE_ID", "MITRE_Technique", "MITRE_Tactic"]
    ).size().reset_index(name="count").sort_values("count", ascending=False).head(5).to_dict(orient="records")

    process_risk = ml_full[ml_full["AnomalyScore_raw"] == -1]["ProcessName"].value_counts().head(5).to_dict()
    chain_summary = chain_risk.head(3).reset_index().to_dict(orient="records")

    return {
        "data_sources": {
        "mordor_simulation": "Empire VBS launcher attack simulation (recorded 2020-09-04)",
        "local_windows_logs": "Live host security and system logs (2025-2026)",
        "note": "Mordor data is a controlled attack simulation, not a live incident"
         },
        "investigation_period": {
            "start": str(ml_full["Timestamp"].min()),
            "end": str(ml_full["Timestamp"].max())
        },
        "total_events_analyzed": len(ml_full),
        "anomalies_detected": int((ml_full["AnomalyScore_raw"] == -1).sum()),
        "anomaly_rate_percent": round((ml_full["AnomalyScore_raw"] == -1).sum() / len(ml_full) * 100, 2),
        "top_anomalous_events": top_anomalies,
        "mitre_techniques_observed": technique_summary,
        "high_risk_processes": process_risk,
        "attack_chain_summary": chain_summary
    }

def generate_forensic_report_llm(context_data: dict, api_key: str) -> str:
    client = Groq(api_key=api_key)

    prompt = f"""You are a senior digital forensics analyst writing an official incident investigation report.\n\nBelow is structured forensic evidence extracted from an automated analysis pipeline.\n\nEVIDENCE SUMMARY:\n{json.dumps(context_data, indent=2, default=str)}\n\nWrite the report in the following structure:\n\n# FORENSIC INVESTIGATION REPORT\n**Classification:** Confidential\n**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n\n## 1. Executive Summary\n## 2. Investigation Timeline\n## 3. Threat Actor Behavior Analysis\n## 4. Key Indicators of Compromise (IOCs)\n## 5. Attack Chain Reconstruction\n## 6. Risk Assessment\n## 7. Recommended Immediate Actions\n## 8. Analyst Notes\n
    Write like a senior analyst. Reference MITRE techniques by ID. Be specific about timestamps and processes.This dataset contains TWO sources: a controlled Mordor attack simulation from 2020\nand live Windows logs from 2025-2026. Clearly distinguish between them in your report."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=4000
    )
    return response.choices[0].message.content

def ingest_and_unify_logs(
    mordor_json_path,
    security_evtx_path,
    system_evtx_path,
    security_json_output_path,
    system_json_output_path,
    perform_evtx_conversion=True
    ):
    # Mount Google Drive
    # drive.mount('/content/drive') # Mounting handled in orchestration cell

    if perform_evtx_conversion:
        print("[*] Converting Security Logs...")
        evtx_to_json_stream(security_evtx_path, security_json_output_path)

        print("[*] Converting System Logs...")
        evtx_to_json_stream(system_evtx_path, system_json_output_path)
        print("[+] EVTX conversion complete.")
    else:
        print("[!] Skipping EVTX conversion. Assuming JSON files already exist.")

    # Load Mordor data
    print("[*] Loading Mordor data...")
    df_mordor = pd.read_json(mordor_json_path, lines=True)

    # Load converted security and system logs
    print("[*] Loading security logs...")
    df_security = pd.read_json(security_json_output_path, lines=True)
    print("[*] Loading system logs...")
    df_system = pd.read_json(system_json_output_path, lines=True)
    print("[+] Logs loaded.")

    # Parse security event XML
    print("[*] Parsing security event XML...")
    security_parsed_data = df_security[0].apply(parse_security_event_xml)
    df_security_details = pd.DataFrame(security_parsed_data.tolist())

    # Parse system event XML
    print("[*] Parsing system event XML...")
    system_parsed_data = df_system[0].apply(parse_system_event_xml)
    df_system_details = pd.DataFrame(system_parsed_data.tolist())
    print("[+] XML parsing complete.")

    # Standardize df_security_details
    df_security_details['Timestamp'] = pd.to_datetime(df_security_details['EventTime'])
    df_security_details = df_security_details.drop(columns=['EventTime'])
    df_security_details['EventType'] = 'Security Event'
    df_security_details['Description'] = 'Security event with ID ' + df_security_details['EventID'].astype(str) + ' from ' + df_security_details['ProviderName']
    df_security_details = df_security_details.rename(columns={'ProviderName': 'Source'})

    # Standardize df_system_details
    df_system_details['Timestamp'] = pd.to_datetime(df_system_details['EventTime'])
    df_system_details = df_system_details.drop(columns=['EventTime'])
    df_system_details['EventType'] = 'System Event'
    df_system_details['Description'] = 'System event with ID ' + df_system_details['EventID'].astype(str) + ' from ' + df_system_details['ProviderName']
    df_system_details = df_system_details.rename(columns={'ProviderName': 'Source'})

    print("[+] Security and System logs standardized.")

    # Normalize Mordor DataFrame
    print("[*] Normalizing Mordor data...")
    df_mordor_normalized = pd.DataFrame() # Initialize empty DataFrame
    # Check if 'EventTime' exists before accessing it
    if 'EventTime' in df_mordor.columns:
        df_mordor_normalized['Timestamp'] = pd.to_datetime(df_mordor['EventTime'])
    else:
        df_mordor_normalized['Timestamp'] = pd.Series(dtype='datetime64[ns]') # Empty series if not found

    df_mordor_normalized['EventType'] = 'Mordor Attack Simulation'
    df_mordor_normalized['Source'] = df_mordor.get('Channel', 'Unknown')
    # df_mordor_normalized['EventID'] = df_mordor.get('EventID', 0)
    df_mordor_normalized['EventID'] = df_mordor.get('EventID', pd.Series(0, index=df_mordor.index))

    target_file = df_mordor.get('TargetFilename', pd.Series(dtype='str'))
    image = df_mordor.get('Image', pd.Series(dtype='str'))
    df_mordor_normalized['Description'] = 'Activity: ' + target_file.fillna(image).fillna('Unknown')
    print("[+] Mordor data normalized.")

    # Concatenate and unify
    print("[*] Unifying all events...")
    common_cols = ['Timestamp', 'EventType', 'Source', 'EventID', 'Description']

    df_unified_events = pd.concat([
        df_security_details[common_cols] if not df_security_details.empty else pd.DataFrame(columns=common_cols),
        df_system_details[common_cols] if not df_system_details.empty else pd.DataFrame(columns=common_cols),
        df_mordor_normalized[common_cols] if not df_mordor_normalized.empty else pd.DataFrame(columns=common_cols)
    ], ignore_index=True)

    df_unified_events['Timestamp'] = pd.to_datetime(df_unified_events['Timestamp'], utc=True)
    df_unified_events = df_unified_events.sort_values(by='Timestamp').reset_index(drop=True)
    print(f"[+] Unified events DataFrame created with {len(df_unified_events)} events.")

    return df_unified_events

def apply_threat_hunting_rules(df_unified_events_input):
    print("[*] Running Threat Hunter Engine...")
    df = df_unified_events_input.copy()

    # Apply the threat hunting engine
    df['Alert'] = df.apply(hunt_threats, axis=1)

    print("[*] Mapping events to MITRE ATT&CK framework...")
    # Apply MITRE mapping
    df[["MITRE_ID", "MITRE_Technique", "MITRE_Tactic"]] = df.apply(map_to_mitre, axis=1)

    mitre_coverage = df[df["MITRE_ID"] != "—"]["MITRE_ID"].nunique()
    print(f"[+] {mitre_coverage} unique MITRE ATT&CK techniques identified.")
    print(df[df["MITRE_ID"] != "—"][["Timestamp","MITRE_ID","MITRE_Technique","MITRE_Tactic"]].head(10).to_string())

    suspicious_events_count = len(df[df['Alert'] != "Normal"])
    print(f"[+] Hunt complete! Found {suspicious_events_count} suspicious events out of {len(df)} total logs.")

    return df

def perform_ml_anomaly_detection(df_unified_events_input):
    print("[*] Building ML feature matrix...")
    ml_df = df_unified_events_input.copy()

    # Encode categorical features
    event_enc = LabelEncoder()
    source_enc = LabelEncoder()
    ml_df["EventID_encoded"] = event_enc.fit_transform(ml_df["EventID"].astype(str))
    ml_df["Source_encoded"] = source_enc.fit_transform(ml_df["Source"].astype(str))

    # Time features
    ml_df["Time_numeric"] = pd.to_datetime(ml_df["Timestamp"], utc=True).astype("int64") // 10**9
    ml_df = ml_df.sort_values("Timestamp").reset_index(drop=True)

    # TimeDelta
    ml_df["TimeDelta"] = ml_df["Time_numeric"].diff().fillna(0)
    ml_df["TimeDelta"] = ml_df["TimeDelta"].clip(upper=3600)

    # ProcessName extraction
    ml_df["ProcessName"] = ml_df["Description"].apply(extract_process)
    process_enc = LabelEncoder()
    ml_df["ProcessName_encoded"] = process_enc.fit_transform(ml_df["ProcessName"])

    # Final feature matrix
    feature_cols = [
        "EventID_encoded",
        "Source_encoded",
        "ProcessName_encoded",
        "Time_numeric",
        "TimeDelta"
    ]
    X = ml_df[feature_cols]

    # Train Isolation Forest
    print("[*] Training Isolation Forest on timeline...")
    model = IsolationForest(
        contamination="auto",
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    )
    ml_df["AnomalyScore_raw"] = model.fit_predict(X)
    ml_df["AnomalyScore_confidence"] = model.decision_function(X)

    # Normalize confidence to RiskScore
    scaler = MinMaxScaler(feature_range=(0, 100))
    ml_df["RiskScore"] = scaler.fit_transform(
        -ml_df["AnomalyScore_confidence"].values.reshape(-1, 1)
    ).flatten().round(1)

    anomaly_count = (ml_df["AnomalyScore_raw"] == -1).sum()
    print(f"[+] Anomaly detection complete. {anomaly_count} anomalous events detected from {len(ml_df)} total.")
    print(f"[+] Anomaly rate: {anomaly_count/len(ml_df)*100:.2f}%")

    return ml_df

def identify_attack_chains(df_unified_events_with_alerts_and_mitre, ml_full_with_risk_scores, time_gap_minutes=2):
    print("[*] Identifying attack chains...")
    # Filter for suspicious events
    threat_df = df_unified_events_with_alerts_and_mitre[df_unified_events_with_alerts_and_mitre["Alert"] != "Normal"].copy()

    # Ensure threat_df has the same index as ml_full_with_risk_scores for accurate RiskScore merging
    # It's crucial that both dataframes originated from df_unified_events and maintain their indices.
    # For this scenario, assuming filtering preserves index alignment for direct assignment.
    threat_df["RiskScore"] = ml_full_with_risk_scores["RiskScore"]

    # Build attack chains using the helper function
    threat_df = build_attack_chains(threat_df, time_gap_minutes=time_gap_minutes)

    # Calculate chain risk summary
    chain_risk = threat_df.groupby("AttackChainID").agg(
        EventCount=("Timestamp", "count"),
        AvgRiskScore=("RiskScore", "mean"),
        MaxRiskScore=("RiskScore", "max"),
        Techniques=("MITRE_ID", lambda x: list(x.dropna().unique())),
        Tactics=("MITRE_Tactic", lambda x: list(x.dropna().unique()))
    ).sort_values("EventCount", ascending=False)

    print("[+] Attack Chain Identification complete.")
    print("[+] Attack Chain Risk Summary (Top 10 by Event Count):")
    print(chain_risk.head(10).to_string())

    return threat_df, chain_risk

def generate_forensic_dashboard(ml_full_with_risk_scores, output_dir):
    print("[*] Generating forensic dashboard visualization...")
    fig = plt.figure(figsize=(16, 10))
    gs = gridspec.GridSpec(2, 2, figure=fig)

    # 1. TimeDelta distribution — looking for bimodal signature of automation
    ax1 = fig.add_subplot(gs[0, :])
    normal_deltas = ml_full_with_risk_scores[ml_full_with_risk_scores["AnomalyScore_raw"] == 1]["TimeDelta"]
    anomaly_deltas = ml_full_with_risk_scores[ml_full_with_risk_scores["AnomalyScore_raw"] == -1]["TimeDelta"]

    ax1.hist(normal_deltas, bins=50, alpha=0.6, color="#2a9d8f", label="Normal Events", density=True)
    ax1.hist(anomaly_deltas, bins=50, alpha=0.7, color="#e63946", label="Anomalous Events", density=True)
    ax1.set_xlabel("Seconds Between Events (TimeDelta)", fontsize=11)
    ax1.set_ylabel("Density", fontsize=11)
    ax1.set_title("Event Timing Distribution: Normal vs Anomalous\n(Machine-speed execution appears as near-zero delta)", fontsize=12, fontweight="bold")
    ax1.legend()
    ax1.set_xlim(0, 300)

    # 2. Risk Score over time — show attack progression
    ax2 = fig.add_subplot(gs[1, 0])
    ax2.scatter(
        ml_full_with_risk_scores["Timestamp"],
        ml_full_with_risk_scores["RiskScore"],
        c=ml_full_with_risk_scores["AnomalyScore_raw"].map({1: "#2a9d8f", -1: "#e63946"}),
        alpha=0.4, s=10
    )
    ax2.set_xlabel("Time")
    ax2.set_ylabel("Risk Score (0-100)")
    ax2.set_title("Risk Score Timeline", fontweight="bold")
    plt.setp(ax2.xaxis.get_majorticklabels(), rotation=30, ha="right")

    # 3. MITRE Tactic frequency
    ax3 = fig.add_subplot(gs[1, 1])
    tactic_counts = ml_full_with_risk_scores[ml_full_with_risk_scores["MITRE_ID"] != "—"]["MITRE_Tactic"].value_counts()
    colors = ["#e63946", "#f4a261", "#e9c46a", "#2a9d8f", "#457b9d", "#6a4c93"]
    tactic_counts.plot(kind="barh", ax=ax3, color=colors[:len(tactic_counts)])
    ax3.set_title("MITRE ATT&CK Tactic Distribution", fontweight="bold")
    ax3.set_xlabel("Event Count")

    plt.suptitle("AI Forensic Pipeline — Threat Analysis Dashboard", fontsize=14, fontweight="bold", y=1.01)
    plt.tight_layout()

    os.makedirs(output_dir, exist_ok=True)
    dashboard_path = os.path.join(output_dir, "forensic_dashboard.png")
    plt.savefig(dashboard_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[+] Dashboard saved to {dashboard_path}")

def generate_ai_report(ml_full_with_risk_scores, chain_risk, groq_api_key, output_dir):
    print("[*] Building forensic context...")
    report_context = build_report_context(ml_full_with_risk_scores, chain_risk)

    print("[*] Calling Groq API to generate forensic report...")
    report_text = generate_forensic_report_llm(report_context, groq_api_key)

    os.makedirs(output_dir, exist_ok=True)
    report_path = os.path.join(output_dir, "forensic_investigation_report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_text)

    print(f"[+] Report saved to {report_path}")
    print("\n" + "="*60)
    print(report_text[:2000])
    return report_text

from google.colab import drive
import os

# 8. Orchestration Cell

print("Starting complete forensic analysis pipeline...")

# Mount Google Drive once at the start of the orchestration
drive.mount('/content/drive')

# 1. Ingest and Unify Logs
print("\n--- Stage 1: Data Ingestion & Unification ---")
df_unified_events = ingest_and_unify_logs(
    mordor_json_path=MORDOR_JSON_PATH,
    security_evtx_path=SECURITY_EVTX_PATH,
    system_evtx_path=SYSTEM_EVTX_PATH,
    security_json_output_path=SECURITY_JSON_OUTPUT_PATH,
    system_json_output_path=SYSTEM_JSON_OUTPUT_PATH,
    perform_evtx_conversion=False # Set to False to skip EVTX conversion
)
print(f"[+] Ingestion & Unification complete. Total events: {len(df_unified_events)}")
print("Head of df_unified_events:")
print(df_unified_events.head(2))

# 2. Apply Threat Hunting Rules and MITRE Mapping
print("\n--- Stage 2: Threat Hunting & MITRE Mapping ---")
df_unified_events_with_alerts_and_mitre = apply_threat_hunting_rules(df_unified_events)
print(f"[+] Threat Hunting & MITRE Mapping complete. Suspicious events: {len(df_unified_events_with_alerts_and_mitre[df_unified_events_with_alerts_and_mitre['Alert'] != 'Normal'])}")
print("Head of df_unified_events_with_alerts_and_mitre (suspicious events):")
print(df_unified_events_with_alerts_and_mitre[df_unified_events_with_alerts_and_mitre['Alert'] != 'Normal'].head(2))

# 3. Perform ML Anomaly Detection
print("\n--- Stage 3: ML Anomaly Detection ---")
ml_full_with_risk_scores = perform_ml_anomaly_detection(df_unified_events_with_alerts_and_mitre)
print(f"[+] ML Anomaly Detection complete. Anomalous events: {(ml_full_with_risk_scores['AnomalyScore_raw'] == -1).sum()}")
print("Head of ml_full_with_risk_scores (anomalous events):")
print(ml_full_with_risk_scores[ml_full_with_risk_scores['AnomalyScore_raw'] == -1].head(2))

# 4. Identify Attack Chains
print("\n--- Stage 4: Attack Chain Identification ---")
threat_df, chain_risk = identify_attack_chains(
    df_unified_events_with_alerts_and_mitre,
    ml_full_with_risk_scores
)
print(f"[+] Attack Chain Identification complete. Total chains: {threat_df['AttackChainID'].nunique()}")
print("Top 3 Attack Chains:")
print(chain_risk.head(3))

# 5. Generate Forensic Dashboard Visualization
print("\n--- Stage 5: Forensic Dashboard Visualization ---")
os.makedirs(OUTPUT_DIR, exist_ok=True)
generate_forensic_dashboard(ml_full_with_risk_scores, OUTPUT_DIR)
print("[+] Forensic Dashboard Generated.")

# 6. Generate AI-Assisted Report
print("\n--- Stage 6: AI-Assisted Report Generation ---")
groq_api_key = userdata.get("GROQ_API_KEY")
report_text = generate_ai_report(ml_full_with_risk_scores, chain_risk, groq_api_key, OUTPUT_DIR)
print("[+] AI-Assisted Report Generated.")

print("\nComplete forensic analysis pipeline execution finished.")

# Display some final summaries
print("\n--- Final Summaries ---")
print("Top 5 processes in anomalous events:")
print(ml_full_with_risk_scores[ml_full_with_risk_scores['AnomalyScore_raw'] == -1]['ProcessName'].value_counts().head(5))
print("\nFirst 5 entries of the main attack timeline (if available): ")
largest_chain_id = chain_risk.sort_values("EventCount", ascending=False).index[0]
main_attack = threat_df[threat_df["AttackChainID"] == largest_chain_id]
attack_timeline = main_attack[["Timestamp", "EventID", "Description", "Alert"]]
print(attack_timeline.head(5))

print(MITRE_MAPPINGS["1102"])

print("NaN RiskScores:", threat_df["RiskScore"].isna().sum())
print("Sample scores:", threat_df["RiskScore"].dropna().head(5).values)

